version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: adonisjs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge
